{ pkgs, lib, config, inputs, ... }:

{
  imports = [
    # Generated by nixos-generate-config during installation — do not edit by hand.
    # Contains your disk UUIDs, detected kernel modules, and filesystem mounts.
    ./hardware-configuration.nix

    # Modules not in common.nix (excluded so embedded hosts stay minimal)
    ../../modules/dev-tooling.nix
    ../../modules/gaming.nix
    ../../modules/remote-desktop.nix
  ];

  networking.hostName = "framework";

  # ── niri Wayland compositor ────────────────────────────────────────────────
  # Using nixpkgs niri (v25.11+) which supports `include` in config.kdl.
  # niri-flake nixosModule was removed as it pins to older v25.08.

  programs.niri.enable = true;

  # niri doesn't ship a display manager — choose one:
  # Option A: login from TTY and run `niri-session` (simplest)
  # Option B: greetd + tuigreet (minimal TUI greeter — recommended)
  services.greetd = {
    enable = true;
    settings.default_session = {
      command = "${pkgs.tuigreet}/bin/tuigreet --time --cmd niri-session";
      user    = "greeter";
    };
  };

  # Companion Wayland applications
  environment.systemPackages = with pkgs; [
    # Backlight control (replaces programs.light which was removed from nixpkgs)
    brightnessctl

    # Status bar
    # waybar removed — DMS manages its own bar

    # App launcher (niri's recommended launcher — fast, Wayland-native)
    # fuzzel removed — DMS has a built-in app launcher

    # Terminal — kitty with tmux integration
    kitty

    # Screen locking and idle management
    swaylock
    swayidle

    # Notifications
    mako

    # X11 app compatibility layer for niri
    # Lets you run apps that don't support Wayland (xwayland-satellite proxies XWayland)
    xwayland-satellite

    # Screenshot
    grim
    slurp  # region selector for grim
    wl-clipboard

    # Polkit agent (needed for GUI apps that require elevated privileges)
    polkit_gnome

    # VLC
    vlc

    # Sakana Fugu profile launcher for Codex CLI
    codex-fugu

    libreoffice
    udiskie

    # File manager
    nautilus

    git-lfs
  ];

  # Polkit — required for apps like GParted, file managers to request sudo
  security.polkit.enable = true;
  systemd.user.services.polkit-gnome = {
    description = "Polkit GNOME agent";
    wantedBy    = [ "graphical-session.target" ];
    wants       = [ "graphical-session.target" ];
    after       = [ "graphical-session.target" ];
    serviceConfig.ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
  };

  # ── Fingerprint reader ────────────────────────────────────────────────────
  # Framework 13 11th-gen has a Goodix fingerprint reader.
  # Enroll fingerprints with: fprintd-enroll

  services.fprintd.enable = true;
  security.pam.services.swaylock.fprintAuth = true; # unlock screen with finger

  # ── NVMe power management ─────────────────────────────────────────────────
  # Prevents the NVMe drive from dropping off the bus during sleep/resume.
  boot.kernelParams = [
    "nvme_core.default_ps_max_latency_us=0"
    "nvme.noacpi=1"  # reduces s2idle suspend drain without the slow-resume cost of deep sleep
  ];
  boot.blacklistedKernelModules = [ "cros-usbpd-charger" ]; # mis-detected on Framework, spams error logs

  # ── /etc/nixos ownership ──────────────────────────────────────────────────
  # Lets the framework user git pull/push without sudo.
  # After first boot run: sudo chown -R framework:users /etc/nixos && sudo chmod -R 775 /etc/nixos
  systemd.tmpfiles.rules = [
    "d /etc/nixos 0775 framework users -"
  ];

  # ── Power management ──────────────────────────────────────────────────────
  # The nixos-hardware Framework module enables power-profiles-daemon and
  # thermald. These are complementary additions.

  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC  = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
      PCIE_ASPM_ON_BAT = "powersupersave";
    };
  };

  # Show battery percentage / status
  services.upower.enable = true;

  # ── Backlight ─────────────────────────────────────────────────────────────
  # acpilight is the correct brightness driver for 11th-gen (nixos-generate-config mis-detects it).
  hardware.acpilight.enable = true;

  # Required for Wayland compositors to detect and manage display brightness via IIO sensor.
  hardware.sensor.iio.enable = true;

  # Fix headphone jack noise/crackling when power management is active.
  # Fix Ethernet expansion card (RTL8156) aggressive autosuspend.
  services.udev.extraRules = ''
    SUBSYSTEM=="pci", ATTR{vendor}=="0x8086", ATTR{device}=="0xa0e0", ATTR{power/control}="on"
    ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="0bda", ATTR{idProduct}=="8156", ATTR{power/autosuspend}="20"
  '';


  # ── Snapshots (btrbk) ─────────────────────────────────────────────────────
  # Daily snapshots of @ and @home into /.snapshots
  # Run manually with: sudo btrbk run --progress
  # List snapshots with: sudo btrbk list

  services.btrbk.instances.btrbk = {
    onCalendar = "daily";
    settings = {
      snapshot_preserve_min = "2d";
      snapshot_preserve     = "7d 4w 6m";
      volume."/btrfs" = {
        snapshot_dir = "@snapshots";
        subvolume."@"     = {};
        subvolume."@home" = {};
      };
    };
  };

  # ── Sudo — allow framework user to rebuild without password ──────────────
  security.sudo.extraRules = [
    {
      users = [ "framework" ];
      commands = [
        {
          command = "/run/current-system/sw/bin/nixos-rebuild";
          options = [ "NOPASSWD" ];
        }
      ];
    }
  ];

  # ── Docker / local Forgejo CI ─────────────────────────────────────────────
  virtualisation.docker.enable = true;
  agentFramework.forgejoCi.enable = true;

  # ── USB auto-mounting ─────────────────────────────────────────────────────
  services.udisks2.enable = true;
  systemd.user.services.udiskie = {
    description = "udiskie auto-mounter";
    wantedBy = [ "graphical-session.target" ];
    after    = [ "graphical-session.target" ];
    serviceConfig.ExecStart = "${pkgs.udiskie}/bin/udiskie --no-tray";
  };

  # ── Bluetooth ─────────────────────────────────────────────────────────────

  hardware.bluetooth = {
    enable    = true;
    powerOnBoot = false; # save battery; enable manually when needed
  };
  services.blueman.enable = true; # GUI bluetooth manager
}
